{% set name = "ormsgpack" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ormsgpack-{{ version }}.tar.gz
  sha256: 6b4c98839cb7fc2a212037d2258f3a22857155249eb293d45c45cb974cfba834

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python


test:
  imports:
    - ormsgpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aviramha/ormsgpack
  summary: Fast, correct Python msgpack library supporting dataclasses, datetimes, and numpy
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT

extra:
  recipe-maintainers:
    - thewchan
