schema_version: 1

context:
  name: ormsgpack
  version: "1.11.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ormsgpack-${{ version }}.tar.gz
  sha256: 7c9988e78fedba3292541eb3bb274fa63044ef4da2ddb47259ea70c05dee4206

build:
  number: 1
  skip: match(python, "<3.8")
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - if: win
      then: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
    - if: unix
      then: export PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - ormsgpack
      pip_check: true

about:
  summary: Fast, correct Python msgpack library supporting dataclasses, datetimes, and numpy
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://github.com/aviramha/ormsgpack

extra:
  recipe-maintainers:
    - thewchan
